language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
# before_install:
#   - export TE_MAVEN_HOME="$(dirname $(which mvn))/.."
#   - export MAVEN_OPTS="-Xms256m -Xmx512m"
# stages:
#   - name: compileFeature
# jobs:
#   include:
#     - stage: compileFeature
#       script:
#       - ./gradlew check install
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh # publishes only if tagged with v.*
