/*
 * generated by Xtext 2.15.0
 */
package org.testeditor.aml.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.testeditor.aml.dsl.AmlRuntimeModule
import org.testeditor.aml.dsl.AmlStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AmlIdeSetup extends AmlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AmlRuntimeModule, new AmlIdeModule))
	}
	
}
